version: '3.8'
services:
  frontend:
    container_name: frontend
    image: httpd:2.4
    ports: 
     - "8080:80"
    volumes:
      - ./index.html:/usr/local/apache2/htdocs/index.html:ro
    networks:
      - frontend
    depends_on:
     - backend     
  backend:
    image:     abdallah279/blog-backend:01
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - frontend
      - backend
    depends_on:
      - database 
  database:
    image: mariadb:10.5
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: blogdb
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend 
networks:
  frontend:
  backend:
volumes:
  db-data:         